### ISSUE TITLE
📝 Add governance instances to the ontology

### ISSUE THREAD

**Issue by ccamel** [okp4/ontology#119]
## Idea

With the inclusion of the governance metadata concept in the ontology (#108), it is now possible to describe the governance of the examples' dataspaces. Let's do it.

## Todo

- [ ] Add the governance metadata instance for `rhizome` dataspace
- [ ] Add the governance metadata instance for `ds4i` dataspace

**Comment by ChaimaaZaoui** [comment]
The ticket is blocked since Chris couldn't continue working on it due to his work load. 
Can @amimart or @bdeneux take care of it ?

**Comment by SonnevilleDamien** [comment]
@MdechampG, @ccamel 

I have submitted a PR where I have completed adding the governance of Rhizome based on my comprehension of the ontology and the information I had in: app.staging.okp4.network.

I have left it in draft mode for now to allow for a review in case there are any mistakes, additionally, I have issues with the ontology linter, but i don't understand why @ccamel. If my comprehension is fine, I will proceed with DS4I next.


https://github.com/okp4/ontology/pull/126

**Comment by ccamel** [comment]
Thanks @SonnevilleDamien. I'll take a look on it today. 
However, due to the structural complexity of the ontological instances, it will soon be desirable to write unit tests (based on [SHACL](https://www.w3.org/TR/shacl/)) on this specific part to better control compliance (see https://github.com/okp4/ontology/pull/56). I'll see how we can introduce it properly, and then you'll have to take over. 😛

**Comment by SonnevilleDamien** [comment]
🫡

**Comment by SonnevilleDamien** [comment]
I just added the governance for DS4I following @ccamel's approval yesterday.
I also fixed a couple of UUIDs where there was an issue.
