### ISSUE TITLE
Core concepts and relationships evolutions - Introduction of Zone

### ISSUE THREAD

**Issue by MdechampG** [okp4/ontology#127]
### Purpose

As presented in the review of 20/04/2023 , we have 
- introduced the concept of `Zone` (wider scope than data space)
- modified the relationships between the different objects : no more "belongs to" relationship between a resource (data or service) and a Data space (Zone)
- Introduced the concept of `Consent` attached to a resource

We should update the ontology to integrate these evolutions.

Here is a scheme of the relationships : 

![image](https://github.com/okp4/ontology/assets/92780073/738d483c-3521-4313-8028-cbac1a500dbe)

### Resources

- [OKP4 Knowledge Sharing through Ontology-Driven Dataverse: A New Approach to Knowledge Description](https://blog.okp4.network/okp4-knowledge-sharing-through-ontology-driven-dataverse-a-new-approach-to-knowledge-description-f9b81d4484c8) describes the concepts of the ontology, including the Zones.
- [Beyond Traditional Governance: Embracing On-Chain with OKP4](https://blog.okp4.network/beyond-traditional-governance-embracing-on-chain-with-okp4-1-3-bb925ea4e1b2) describes the governance concepts to include in the ontology.

**Comment by MdechampG** [comment]
@ccamel can we close this issue ?

**Comment by ccamel** [comment]
@MdechampG yes!
