### ISSUE TITLE
🐛 `make format-rdf` goal fails

### ISSUE THREAD

**Issue by ccamel** [okp4/ontology#82]
# Bug Report

The `make format-rdf` goal fails. 

## What did you expect to see?

I expect the ontology source files to be formatted when running `make format-rdf`.

## What did you see instead?

```
➜ make format-rdf
📐 Formating: src/core.ttl
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

### What operating system are you using (such as macOS, Linux and Windows)?

- macOS Ventura 13.1
- Apple M1
- Docker Desktop 4.16.1

**Comment by ccamel** [comment]
I propose to make the contribution on the project [owl-cli](https://github.com/atextor/owl-cli) to benefit from a docker image ready to use - See issue https://github.com/atextor/owl-cli/issues/9.

**Comment by ChaimaaZaoui** [comment]
@ccamel @bdeneux any progress about this ticket ?
